### ISSUE TITLE
Is there a way to disable the editor and only display the content editing?

### ISSUE THREAD

**Issue by bhaskardabhi** [wxik/react-native-rich-editor#65] opened 2020-07-18 12:55 UTC
Is there a way to disable the content editing? I tried webview but it looks so different in webview then the editor.

**Comment by stulip** [comment] 2020-07-19 07:35
Duplicate of #63

**Closed by stulip** 2020-07-19 07:35 UTC

**Comment by bhaskardabhi** [comment] 2020-07-19 11:11
@stulip 

disabled doesn't seem to work. I passed `disable` true still use it able to type:
Below is my code:

```
<RichEditor
                        // initialFocus={true}
                        editorStyle={contentStyle} // default light style
                        ref={that.richText}
                        style={[styles.rich]}
                        placeholder={'please input content'}
                        initialContentHTML={this.props.content || ''}
                        disabled={true}
                        editorInitializedCallback={that.editorInitializedCallback}
                        onChange={that.handleChange}
                        onHeightChange={that.handleHeightChange}
                    />
```

Following my dependencies:
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-pell-rich-editor": "^1.3.0",
    "react-native-webview": "^10.3.2"

RN:

**Comment by stulip** [comment] 2020-07-19 11:33
@bhaskardabhi Please provide the following, phone model and version

**Comment by bhaskardabhi** [comment] 2020-07-19 13:03
I am using Android emulator with Pixel 3a XL API 27 and OS Android 8.1 x86

**Comment by stulip** [comment] 2020-07-19 15:16
`Pixel 3a XL API 27 and OS Android 8.1 x86` Tested, and no problem with `disabled`

I found that there is a problem with scrollview and keyboard

**Comment by bhaskardabhi** [comment] 2020-07-19 15:58
@stulip can you paste ur code if possible? Also having Editor inside scrollview or view with flex won't affect the disabling functionality right?

Yes i have faced issue with scrollview and keyboard as well.

**Comment by stulip** [comment] 2020-07-19 16:01
The source code contains [examples](https://github.com/wxik/react-native-rich-editor/tree/master/examples)

**Comment by AkalUstat** [comment] 2020-09-25 00:41
I am also having issues with disabled prop @stulip no longer working for me
